[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/:page.html"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/:path/:page.html"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/yardi-consulation-services"
  to = "/yardi-consultation-services"
  status = 301
  force = true

[[redirects]]
  from = "/yardi-consulation-services/"
  to = "/yardi-consultation-services"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
